"""add arabic col and mark schemes

Revision ID: 2ef9e254bb24
Revises: 0003_school_code_subject_section
Create Date: 2026-08-20 05:11:48.759644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef9e254bb24'
down_revision = '0003_school_code_subject_section'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_mark_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('comp1_label', sa.String(length=30), nullable=True),
    sa.Column('comp1_max', sa.Float(), nullable=True),
    sa.Column('comp2_label', sa.String(length=30), nullable=True),
    sa.Column('comp2_max', sa.Float(), nullable=True),
    sa.Column('comp3_label', sa.String(length=30), nullable=True),
    sa.Column('comp3_max', sa.Float(), nullable=True),
    sa.Column('comp4_label', sa.String(length=30), nullable=True),
    sa.Column('comp4_max', sa.Float(), nullable=True),
    sa.Column('comp5_label', sa.String(length=30), nullable=True),
    sa.Column('comp5_max', sa.Float(), nullable=True),
    sa.Column('comp6_label', sa.String(length=30), nullable=True),
    sa.Column('comp6_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'section', name='uq_school_section_scheme')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_coupons_code'))
        batch_op.drop_index(batch_op.f('ix_coupons_code'))
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=True)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_arabic_column', sa.Boolean(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_transcript_coupon'))
        batch_op.drop_index(batch_op.f('uq_student_transcript_coupon'))
        batch_op.drop_index(batch_op.f('uq_students_admission_number'))
        batch_op.drop_index(batch_op.f('ix_students_admission_number'))
        batch_op.create_index(batch_op.f('ix_students_admission_number'), ['admission_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_transcript_coupon'), ['transcript_coupon'], unique=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arabic_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('uq_users_username'), ['username'], unique=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('arabic_name')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_transcript_coupon'))
        batch_op.drop_index(batch_op.f('ix_students_admission_number'))
        batch_op.create_index(batch_op.f('ix_students_admission_number'), ['admission_number'], unique=False)
        batch_op.create_index(batch_op.f('uq_students_admission_number'), ['admission_number'], unique=True)
        batch_op.create_index(batch_op.f('uq_student_transcript_coupon'), ['transcript_coupon'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_transcript_coupon'), ['transcript_coupon'], unique=False)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('show_arabic_column')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_code'))
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('uq_coupons_code'), ['code'], unique=True)

    op.drop_table('section_mark_schemes')
    # ### end Alembic commands ###
